name: Clone Prod DB to Staging
on:
  workflow_dispatch: {}
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Clone DB (public schema only)
        env:
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          STG_DATABASE_URL:  ${{ secrets.STG_DATABASE_URL }}
        run: |
          set -euo pipefail
          echo "Dumping PROD (schema: public) ..."
          pg_dump "$PROD_DATABASE_URL" -n public -Fc -v -f dump.bin
          echo "Restoring into STAGING (schema: public, no owner/privs) ..."
          pg_restore -v --no-owner --no-privileges -n public -c -d "$STG_DATABASE_URL" dump.bin
          echo "Clone complete."

